name: Build and Deploy Docker Image to Azure octopus
on:
  push:
    branches:
      - main
permissions:
  id-token: write
  contents: read
env:
  AZURE_CONTAINER_REGISTRY: azurepoc123
  Resource_Group: cfsh-cc-d-rg02
  CONTAINER_APP_NAME: azurepoc123
jobs:
  build-and-deploy:
    name: Build and Push Docker Image to ACR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Login to Azure
        uses: azure/login@v2
        with:
           creds: ${{ secrets.AZURE_CREDENTIALS }}
        
      - name: Login to Azure
        uses: docker/login-action@v3
        with:
          registry: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io
          username: ${{ secrets.ACR_NAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - name: PUSH TO ACR
        uses: docker/build-push-action@v6
        with:
           push: true
           tags: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.CONTAINER_APP_NAME }}:${{ github.sha }}
           file: Dockerfile

      - name: Azure Login Web App
        uses: azure/webapps-deploy@v3
        with:
          #client-id: ${{ secrets.AZURE_CLIENT_ID }}
          #tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          #subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
           #creds: ${{ secrets.AZURE_CREDENTIALS }}
           #allow-no-subscriptions: true
          #enable-AzPSSession: true
          #scope-level: 'managementgroup'
          #azcliversion: latest

      #- name: Deploy to webapp
       # uses: azure/container-apps-deploy-action@v1
        #with: 
           app-name: ${{ secrets.APP_NAME }}
           images: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.CONTAINER_APP_NAME }}:${{ github.sha }}
           #resourceGroup: ${{ env.Resource_Group }}
           #containerAppName: ${{ env.CONTAINER_APP_NAME }}
